# Generated by Django 5.2.1 on 2025-08-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
