# Generated by Django 5.2.1 on 2025-08-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikiarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='rendered_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
