# Generated by Django 5.2.1 on 2025-08-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_category_alter_wikiarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.wikiarticle'),
        ),
    ]
