# Generated by Django 5.2.1 on 2025-08-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_wikiarticle_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikiarticle',
            name='parent',
        ),
    ]
