# Generated by Django 5.2.1 on 2025-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='e.g. g, ml, piece(s)', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit in EUR', max_digits=10)),
            ],
        ),
    ]
