# Generated by Django 5.2.1 on 2025-06-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_unit',
        ),
    ]
