# Generated by Django 5.2.1 on 2025-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/avatar_placeholder.png', null=True, upload_to='users/avatars/'),
        ),
    ]
