services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  frontend:
    build:
      context: ./app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
