[project]
name = "gourmet-wiki"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.1",
    "django-allauth>=65.9.0",
    "django-cotton>=2.1.2",
    "django-formtools>=2.5.1",
    "django-vite>=3.1.0",
    "pillow>=11.2.1",
]
