# Generated by Django 5.2.1 on 2025-12-17 23:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='recipes/images/')),
                ('course_type', models.CharField(choices=[('amuse_bouche', 'Amuse-bouche'), ('cold_starter', "Hors d'œuvre"), ('soup', 'Potage'), ('fish', 'Poisson'), ('hot_starter', 'Entrée'), ('main', 'Plat de Résistance'), ('sorbet', 'Sorbet'), ('roast', 'Rôti'), ('vegetable', 'Légumes'), ('salad', 'Salade'), ('cheese', 'Fromage'), ('dessert', 'Dessert'), ('digestive_drink', 'Digestif')], default='main', max_length=50, verbose_name='Course')),
                ('portions', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Portions')),
                ('cooking_time_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cooking Time (Minutes)')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=50, verbose_name='Skill Level')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorite_by', models.ManyToManyField(blank=True, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipePreparationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_text', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField()),
                ('is_section', models.BooleanField(default=False, help_text='Marks this row as a section/category break instead of a regular step.')),
                ('section_title', models.CharField(blank=True, default='', max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_steps', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('unit', models.CharField(choices=[('piece', 'piece'), ('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('oz', 'oz'), ('sp', 'sp'), ('tes', 'tes')], default='g', max_length=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recipe', 'user')},
            },
        ),
    ]
