# Generated by Django 5.2.1 on 2025-12-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepreparationstep',
            name='is_section',
            field=models.BooleanField(default=False, help_text='Marks this row as a section/category break instead of a regular step.'),
        ),
        migrations.AddField(
            model_name='recipepreparationstep',
            name='section_title',
            field=models.CharField(blank=True, default='', help_text='Title of the section/category (e.g., Sauce, Meat)', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipepreparationstep',
            name='step_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
