# Generated by Django 5.2.1 on 2025-12-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipepreparationstep_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepreparationstep',
            name='section_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
