# Generated by Django 5.2.1 on 2025-12-21 18:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)], verbose_name='Recipe Name'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('piece', 'piece'), ('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('oz', 'oz'), ('sp', 'sp'), ('tes', 'tes')], default='g', max_length=10, verbose_name='Unit'),
        ),
    ]
