# Generated by Django 5.2.1 on 2025-12-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_name_alter_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepreparationstep',
            name='section_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='recipepreparationstep',
            name='step_text',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Step'),
        ),
    ]
