# Generated by Django 5.2.1 on 2025-12-22 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipepreparationstep_section_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepreparationstep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe'),
        ),
    ]
