# Generated by Django 5.2.1 on 2025-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipepreparationstep_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepreparationstep',
            name='is_section',
            field=models.BooleanField(default=False, help_text='Marks this row as a section/category break instead of a regular step.', verbose_name='Is Section'),
        ),
    ]
