# Generated by Django 5.2.1 on 2025-06-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.CreateModel(
            name='RecipePreparationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_text', models.TextField(max_length=500)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_steps', to='recipes.recipe')),
            ],
        ),
    ]
