# Generated by Django 5.2.1 on 2025-06-22 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipeimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='skill_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('piece', 'piece'), ('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('oz', 'oz'), ('sp', 'sp'), ('tes', 'tes')], default='g', max_length=10),
        ),
    ]
