# Generated by Django 5.2.1 on 2025-12-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published at'),
        ),
    ]
