# Generated by Django 5.2.1 on 2025-06-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_recipe_favorite_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.CharField(max_length=150),
        ),
    ]
