# Generated by Django 5.2.1 on 2025-12-27 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipe_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.PositiveIntegerField(blank=True, default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cooking Time (Minutes)'),
        ),
    ]
