# Generated by Django 5.2.1 on 2026-01-05 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_cooking_time_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
