# Generated by Django 5.2.1 on 2026-01-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipeimage_options_recipeimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(help_text='Select multiple images to upload', upload_to='recipes/images/', verbose_name='Upload Image'),
        ),
    ]
