# Generated by Django 5.2.1 on 2026-01-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_recipeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Description'),
        ),
    ]
