# Generated by Django 5.2.1 on 2025-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_reciperating_rated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='course_type',
            field=models.CharField(choices=[('amuse_bouche', 'Amuse-bouche'), ('cold_starter', "Hors d'œuvre"), ('soup', 'Potage'), ('fish', 'Poisson'), ('hot_starter', 'Entrée'), ('main', 'Plat de Résistance'), ('sorbet', 'Sorbet'), ('roast', 'Rôti'), ('vegetable', 'Légumes'), ('salad', 'Salade'), ('cheese', 'Fromage'), ('dessert', 'Dessert'), ('digestive_drink', 'Digestif')], default='main', max_length=50),
        ),
    ]
