# Generated by Django 5.2.1 on 2025-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_recipe_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Price per unit in EUR', max_digits=10),
        ),
    ]
