# Generated by Django 5.2.1 on 2026-01-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
