# Generated by Django 5.2.1 on 2025-08-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_alter_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rest_time_hours',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rest_time_minutes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='working_time_hours',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='working_time_minutes',
        ),
    ]
