# Generated by Django 5.2.1 on 2026-01-20 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_alter_recipe_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cooking Time (Minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='course_type',
            field=models.CharField(choices=[('amuse_bouche', 'Amuse-bouche'), ('cold_starter', "Hors d'œuvre"), ('soup', 'Potage'), ('fish', 'Poisson'), ('hot_starter', 'Entrée'), ('main', 'Plat de Résistance'), ('sorbet', 'Sorbet'), ('roast', 'Rôti'), ('vegetable', 'Légumes'), ('salad', 'Salade'), ('cheese', 'Fromage'), ('dessert', 'Dessert'), ('digestive_drink', 'Digestif')], default='main', max_length=50, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=50, verbose_name='Skill Level'),
        ),
    ]
