# Generated by Django 5.2.1 on 2025-12-17 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='users/avatars/avatar_placeholder.png', null=True, upload_to='users/avatars/')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=50)),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('member', 'Member'), ('author', 'Author'), ('expert', 'Expert'), ('curator', 'Curator'), ('admin', 'Admin')], default='member', max_length=20)),
                ('points', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(choices=[('1', 'Kitchen Newbie'), ('2', 'Recipe Explorer'), ('3', 'Kitchen Connoisseur'), ('4', 'Knowledge Contributor'), ('5', 'Community Pioneer'), ('6', 'Professional Author'), ('7', 'Kitchen Mentor'), ('8', 'Gourmet Master')], default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(choices=[('member', 'Member')], max_length=30)),
                ('awarded_at', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.profile')),
            ],
            options={
                'unique_together': {('profile', 'badge')},
            },
        ),
    ]
