# Generated by Django 5.2.1 on 2026-01-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='policy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
