# Generated by Django 5.2.1 on 2025-07-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=50),
        ),
    ]
