# Generated by Django 5.2.1 on 2025-07-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_badge_profile_level_profile_points_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.CharField(choices=[('member', 'Member')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
