# Generated by Django 5.2.1 on 2025-07-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userbadge_badge_delete_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='awarded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
