# Generated by Django 5.2.1 on 2025-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userbadge_awarded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('1', 'Küchenneuling'), ('2', 'Rezeptentdecker:in'), ('3', 'Küchenkenner:in'), ('4', 'Wissensstifter:in'), ('5', 'Community-Vorreiter:in'), ('6', 'Fachautor:in'), ('7', 'Küchenmentor:in'), ('8', 'GourmetMaster:in')], default='1', max_length=50),
        ),
    ]
