# Generated by Django 5.2.1 on 2025-08-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('1', 'Kitchen Newbie'), ('2', 'Recipe Explorer'), ('3', 'Kitchen Connoisseur'), ('4', 'Knowledge Contributor'), ('5', 'Community Pioneer'), ('6', 'Professional Author'), ('7', 'Kitchen Mentor'), ('8', 'Gourmet Master')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('member', 'Member'), ('author', 'Author'), ('expert', 'Expert'), ('curator', 'Curator'), ('admin', 'Admin')], default='member', max_length=20),
        ),
    ]
