# Generated by Django 5.2.1 on 2025-08-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_category_ingredient_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_nutrient_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('unit_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fdc_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='IngredientNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='ingredients.ingredient')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.nutrient')),
            ],
            options={
                'unique_together': {('ingredient', 'nutrient')},
            },
        ),
    ]
