# Generated by Django 5.2.1 on 2025-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_nutrient_ingredient_fdc_id_ingredientnutrient'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='wweia_fc_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
