# Generated by Django 5.2.1 on 2025-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_ingredient_description_ingredient_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='nutrient',
            name='unit',
            field=models.CharField(choices=[('piece', 'piece'), ('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('oz', 'oz'), ('sp', 'sp'), ('tes', 'tes')], default='g', max_length=10),
        ),
    ]
