# Generated by Django 5.2.1 on 2025-08-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_remove_nutrient_unit_name_nutrient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
    ]
