# Generated by Django 5.2.1 on 2025-08-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_remove_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
