# Generated by Django 5.2.1 on 2025-08-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_remove_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
