# Generated by Django 5.2.1 on 2025-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0011_nutrient_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
