# Generated by Django 5.2.1 on 2025-08-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0012_ingredientlookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
