# Generated by Django 5.2.1 on 2025-08-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0013_alter_ingredient_slug_alter_nutrient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
