# Generated by Django 5.2.1 on 2025-08-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0014_alter_ingredient_name_alter_ingredient_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('wweia_fc_code', 'name')},
        ),
    ]
