# Generated by Django 5.2.1 on 2025-08-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0016_ingredientlookup_category_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('fdc_id', 'name')},
        ),
    ]
