# Generated by Django 5.2.1 on 2025-08-13 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0017_alter_ingredient_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(default='de', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='ingredients.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'language_code')},
            },
        ),
    ]
