# Generated by Django 5.2.1 on 2025-08-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0020_alter_category_unique_together_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='nutrient',
            unique_together={('fdc_nutrient_id', 'name')},
        ),
    ]
