# Generated by Django 5.2.1 on 2025-08-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0021_alter_nutrient_name_alter_nutrient_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
