# Generated by Django 5.2.1 on 2025-11-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0022_alter_nutrient_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='fdc_id',
        ),
    ]
