# Generated by Django 5.2.1 on 2025-11-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0023_alter_ingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='category',
        ),
        migrations.DeleteModel(
            name='IngredientLookup',
        ),
        migrations.AlterUniqueTogether(
            name='ingredientnutrient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ingredientnutrient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrient',
            name='nutrient',
        ),
        migrations.AlterUniqueTogether(
            name='ingredienttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ingredienttranslation',
            name='ingredient',
        ),
        migrations.AlterUniqueTogether(
            name='nutrient',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='CategoryTranslation',
        ),
        migrations.DeleteModel(
            name='IngredientNutrient',
        ),
        migrations.DeleteModel(
            name='Nutrient',
        ),
        migrations.DeleteModel(
            name='IngredientTranslation',
        ),
    ]
