# Generated by Django 5.2.1 on 2025-12-17 23:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('portions', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('amuse_bouche', 'Amuse-bouche'), ('cold_starter', "Hors d'œuvre"), ('soup', 'Potage'), ('fish', 'Poisson'), ('hot_starter', 'Entrée'), ('main', 'Plat de Résistance'), ('sorbet', 'Sorbet'), ('roast', 'Rôti'), ('vegetable', 'Légumes'), ('salad', 'Salade'), ('cheese', 'Fromage'), ('dessert', 'Dessert'), ('digestive_drink', 'Digestif')], max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='menus.menu')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('menu', 'course_type')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu')),
                ('menu_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.menucourse')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe')),
            ],
            options={
                'unique_together': {('menu', 'menu_course')},
            },
        ),
    ]
