# Generated by Django 5.2.1 on 2025-06-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0019_recipe_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('amuse_bouche', 'Amuse-bouche'), ('cold_starter', "Hors d'œuvre"), ('soup', 'Potage'), ('fish', 'Poisson'), ('hot_starter', 'Entrée'), ('main', 'Plat de Résistance'), ('sorbet', 'Sorbet'), ('roast', 'Rôti'), ('vegetable', 'Légumes'), ('salad', 'Salade'), ('cheese', 'Fromage'), ('dessert', 'Dessert'), ('digestive_drink', 'Digestif')], max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='menus.menutype')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('menu_type', 'course_type')},
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.menutype')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu')),
                ('menu_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.menucourse')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe')),
            ],
            options={
                'unique_together': {('menu', 'menu_course')},
            },
        ),
    ]
