# Generated by Django 5.2.1 on 2025-07-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menu_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_type',
        ),
    ]
