# Generated by Django 5.2.1 on 2025-07-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_remove_menu_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucourse',
            name='menu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='menus.menu'),
            preserve_default=False,
        ),
    ]
