# Generated by Django 5.2.1 on 2025-07-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_menucourse_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuType',
        ),
    ]
