# Generated by Django 5.2.1 on 2025-07-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_menu_created_by_menucoursestep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuCourseStep',
        ),
    ]
