"""
Django settings for gourmet_wiki project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import logging
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

logger = logging.getLogger('allauth')
logger.setLevel(logging.DEBUG)

logging.basicConfig(
    format='%(levelname)s:%(name)s:%(message)s',
    level=logging.DEBUG
)

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'pages.apps.PagesConfig',
    'recipes.apps.RecipesConfig',
    'ingredients.apps.IngredientsConfig',
    'core.apps.CoreConfig',
    'users.apps.UsersConfig',
    'menus.apps.MenusConfig',
    'wiki.apps.WikiConfig',

    # 'rest_framework',
    'corsheaders',
    'django_vite',
    'django_cotton',
    'easy_thumbnails',
    'formtools',
    'crispy_forms',
    'crispy_daisyui',
    # 'reversion',

    'allauth',
    'allauth.account',

    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Enable locale resolution (uses browser Accept-Language and user session)
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.ForceGermanMiddleware',  # disabled to allow language switching
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'core.middleware.RequireLoginMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'users.middleware.HTMXLoginRedirectMiddleware',
    'core.middleware.SuspiciousRequestMiddleware',
    # 'gourmet_wiki.middleware.GlobalRateLimitMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'gourmet_wiki.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'loaders': [(
                'django.template.loaders.cached.Loader',
                [
                    'django_cotton.cotton_loader.Loader',
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ],
            )],
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.debug',
                'core.context_processors.seo_defaults',
                'gourmet_wiki.context_processors.cb_id',
                'gourmet_wiki.context_processors.ga_id',
            ],
            'builtins': [
                'django_cotton.templatetags.cotton'
            ],
        },
    },
]

WSGI_APPLICATION = 'gourmet_wiki.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('WEB_POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'de'  # en-us

LANGUAGES = [
    ('en', 'English'),
    ('de', 'German'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_L10N = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'assets',
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "manifest_path": BASE_DIR / "assets" / ".vite" / "manifest.json",
        "dev_server_port": 5173,
        "dev_server_host": "localhost",
    }
}


#########################
# CORE ACCOUNT SETTINGS #
#########################

AUTH_USER_MODEL = 'users.CustomUser'
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*"]
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_RATE_LIMITS = {
    "login_failed": "5/5m",
}

## REDIRECTS

LOGIN_REDIRECT_URL = 'profile'
ACCOUNT_SIGNUP_REDIRECT_URL = 'profile'
LOGOUT_REDIRECT_URL = '/'

## LOGOUT SECURITY

ACCOUNT_LOGOUT_ON_GET = False

## SESSION / REMEMBER ME

ACCOUNT_SESSION_REMEMBER = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 Tage
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

## EMAIL VERIFICATION

if DEBUG:
    ACCOUNT_EMAIL_VERIFICATION = 'none'
    # ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
else:
    ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_RESEND = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

## SOCIAL LOGIN

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        'SCOPE': ["profile", "email"],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
        'EMAIL_AUTHENTICATION': True,
    }
}

## CUSTOM HOOKS

ACCOUNT_FORMS = {
    'signup': 'users.forms.CustomSignupForm',
}

ACCOUNT_ADAPTER = 'users.adapter.CustomAccountAdapter'
# SOCIALACCOUNT_ADAPTER = "users.adapter.CustomSocialAccountAdapter"


################
# DJANGO SITES #
################

SITE_ID = 1


##################
# OTHER SETTINGS #
##################

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = 'noreply@gourmet-wiki.app'

INTERNAL_IPS = ['127.0.0.1']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'allauth': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173 http://localhost:8000').split(' ')

CSP_DEFAULT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "http://localhost:5173")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "http://localhost:5173")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "http://localhost:5173")
CSP_CONNECT_SRC = ("'self'", "ws://localhost:5173", "http://localhost:5173")

# Add WHITENOISE for a static file serving in production
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000').split(' ')

if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"  # or leave default
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_SSL_REDIRECT = False
else:
    # Required when behind reverse proxy / load balancer
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"
    SECURE_SSL_REDIRECT = True

CRISPY_ALLOWED_TEMPLATE_PACKS = 'daisyui'
CRISPY_TEMPLATE_PACK = 'daisyui'

# --- SEO defaults ---
SITE_NAME = os.getenv('SITE_NAME', 'Gourmet Wiki')
SITE_URL = os.getenv('SITE_URL', 'https://gourmet-wiki.app')
DEFAULT_DESCRIPTION = os.getenv('DEFAULT_DESCRIPTION', 'Discover, cook, and master gourmet recipes.')
DEFAULT_KEYWORDS = os.getenv('DEFAULT_KEYWORDS', 'gourmet recipes, recipe wiki, cooking techniques, ingredient guides')
DEFAULT_OG_IMAGE = os.getenv('DEFAULT_OG_IMAGE', STATIC_URL + 'favicons/android-chrome-512x512.png')

LISTMONK_API_USERNAME = os.getenv('LISTMONK_API_USERNAME')
LISTMONK_API_URL = os.getenv('LISTMONK_API_URL')
LISTMONK_API_TOKEN = os.getenv('LISTMONK_API_TOKEN')

USDA_FDC_API_KEY = os.getenv('USDA_FDC_API_KEY')
USDA_FDC_BASE_URL = "https://api.nal.usda.gov/fdc/v1"

OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL')

VITE_GA_ID=os.getenv('VITE_GA_ID')
VITE_CB_ID=os.getenv('VITE_CB_ID')

APPEND_SLASH = True

THUMBNAIL_ALIASES = {
    '': {
        'hero': {'size': (1920, 1080), 'crop': True},
        'hero_medium': {'size': (1024, 576), 'crop': True},
        'hero_small': {'size': (640, 360), 'crop': True},
    },
}