#!/bin/bash
set -e

# Create and write to debug log (no +x needed on log file)
echo "Loaded env: EMT user is ${EMT_POSTGRES_USER}" > /tmp/debug.log

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE "${WEB_POSTGRES_DB}";
    CREATE DATABASE "${EMT_POSTGRES_DB}";

    CREATE USER "${WEB_POSTGRES_USER}" WITH PASSWORD '${WEB_POSTGRES_PASSWORD}';
    CREATE USER "${EMT_POSTGRES_USER}" WITH PASSWORD '${EMT_POSTGRES_PASSWORD}';

    GRANT ALL PRIVILEGES ON DATABASE "${WEB_POSTGRES_DB}" TO "${WEB_POSTGRES_USER}";
    GRANT ALL PRIVILEGES ON DATABASE "${EMT_POSTGRES_DB}" TO "${EMT_POSTGRES_USER}";
EOSQL
