#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE ${WEB_POSTGRES_DB};
    CREATE DATABASE ${EMT_POSTGRES_DB};

    CREATE USER ${POSTGRES_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';
    CREATE USER ${WEB_POSTGRES_USER} WITH PASSWORD '${WEB_POSTGRES_PASSWORD}';
    CREATE USER ${EMT_POSTGRES_USER} WITH PASSWORD '${EMT_POSTGRES_PASSWORD}';

    GRANT ALL PRIVILEGES ON DATABASE ${WEB_POSTGRES_DB} TO ${WEB_POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${EMT_POSTGRES_DB} TO ${EMT_POSTGRES_USER};
EOSQL
