# Generated by Django 5.2.1 on 2025-06-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeimage_options_remove_recipeimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), ('oz', 'oz'), ('sp', 'sp'), ('tes', 'tes')], default='g', max_length=10),
        ),
    ]
