# Generated by Django 5.2.1 on 2025-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_thumbnail_image_recipepreparationstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepreparationstep',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipepreparationstep',
            name='step_text',
            field=models.CharField(max_length=500),
        ),
    ]
