# Generated by Django 5.2.1 on 2025-06-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipepreparationstep_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
