# Generated by Django 5.2.1 on 2025-06-25 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipeingredient_quantity_reciperating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_hours',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='h'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='min'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rest_time_hours',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='h'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rest_time_minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='min'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='working_time_hours',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='h'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='working_time_minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='min'),
        ),
    ]
