# Generated by Django 5.2.1 on 2025-06-25 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipe_cooking_time_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperating',
            name='rated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
