# Generated by Django 5.2.1 on 2025-07-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menucourse_menu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menucourse',
            unique_together={('menu', 'course_type')},
        ),
        migrations.RemoveField(
            model_name='menucourse',
            name='menu_type',
        ),
    ]
