# Generated by Django 5.2.1 on 2025-07-04 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_delete_menutype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MenuCourseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField()),
                ('menu_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='menus.menucourse')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
